apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-phplumen
spec:
  schedule: "* * * * *"
  jobTemplate:
    metadata:
      labels:
        app: mycronjob
    spec:
      containers:
      - name: php
        image: php:7.2-fpm
        command:
        - /usr/local/bin/php
        - /var/www/html/lumen57/artisan
        - schedule:run >> /dev/null 2>&1 &
        ports:
        - name: http-php
          containerPort: 9000
        volumeMounts:
        - name: php-code
          mountPath: /var/www/html/
      restartPolicy: OnFailure
      volumes:
      - name: php-code
        nfs:
          path: /home/data
          server: 192.168.83.143