apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-example
spec:
  schedule: "* * * * *"
  jobTemplate:
    metadata:
      labels:
        app: mycronjob
    spec:
      containers:
      - name: myjob
        image: alpine
        command:
        - /bin/sh
        - -c
        - date; echo Hello from k8s cluster; sleep 10
      restartPolicy: OnFailure