apiVersion: v1                      
kind: Service                       
metadata:                           
  name: nginx-svc-test2                 
spec:                               
  selector:                         
    name: nginx-test2     
  ports:                            
  - port: 80                        
    name: http                      
    targetPort: 80                  
    protocol: TCP                   
                                    
---                                 
apiVersion: apps/v1                 
kind: Deployment                    
metadata:                           
  name: nginx-deploy-test2         
spec:                               
  replicas: 1                       
  selector:                         
    matchLabels:                    
      name: nginx-test2        
  template:                         
    metadata:                       
      labels:                       
        name: nginx-test2               
    spec:                           
      containers:                   
      - name: nginx                 
        image: nginx:1.17           
        imagePullPolicy: IfNotPresent
        ports:                      
        - name: http                
          containerPort: 80         
        volumeMounts:               
        - name: nginx-config        
          mountPath: /etc/nginx/conf.d
        - name: html                
          mountPath: /usr/share/nginx/html
      volumes:                      
      - name: nginx-config          
        configMap:                  
          name: nginx-config        
          items:                    
          - key: test2.conf         
            path: default.conf        
      - name: html                  
        nfs:                        
          path: /home/data/html     
          server: 192.168.83.143    