apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-config
data:
    test1.conf: |
      server {
            listen       80;
            server_name  localhost;
            
            access_log  /var/log/nginx/host_access.log;
            error_log  /var/log/nginx/host_error.log debug;
            location / {
                index  index.php;
                try_files $uri $uri/ /index.php?$query_string;
            }

            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }

            location ~ \.php$ {
                root   /var/www/html/lumen57/public;
                fastcgi_pass   php-svc.default.svc.cluster.local:9000;
                fastcgi_index  index.php;
                fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
                include        fastcgi_params;
            }
        }

    test2.conf: |
      server {
            listen       80;
            server_name  localhost;
            
            access_log  /var/log/nginx/host_access.log;
            error_log  /var/log/nginx/host_error.log debug;
            location / {
                index  index.php;
                try_files $uri $uri/ /index.php?$query_string;
            }

            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }

            location ~ \.php$ {
                root   /var/www/html/test2;
                fastcgi_pass   php-svc.default.svc.cluster.local:9000;
                fastcgi_index  index.php;
                fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
                include        fastcgi_params;
            }
        }
