apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-pv
  namespace: default
  labels:
    nfspv: php-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.83.143
    path: /home/data