apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pvc2
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 400Mi
  selector:
    matchLabels:
      nfspv: php-data